### PR TITLE
added touch events | added a example page and fixed a bug.

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by KaneCohen** [comment]
Hey @prisis, thanks a lot for the PR. Could you point to the bug? Diff is not helpful with tracking it at all.

**Comment by prisis** [comment]
Hey @KaneCohen, yes 
~~~js
old:
                position = position != 'left' || position != 'right' ? 'right' : position;

                if (v.follow.x) {
                    p.left = e.pageX - win.left + 9;
                }

                if (v.follow.y) {
                    p.top = e.pageY - (tb.height/2) - win.top + 2;
                }
new:
                // Not the same behavior like on the example page
                position = position == 'auto' ? 'right' : position;
                // You forgot "this" on https://github.com/KaneCohen/tooltip/blob/master/tip.js#L198
                if (this.v.follow.x) {
                    p.left = e.pageX - win.left + 9;
                }

                if (this.v.follow.y) {
                    p.top = e.pageY - (tb.height/2) - win.top + 2;
                }
~~~

**Comment by prisis** [comment]
And do you follow SemVer?
If, yes i change the version to 0.2 not 0.1.1

**Comment by KaneCohen** [comment]
@prisis ok got it. Yes, please bump version to 0.2.0.

Otherwise looks good, appreciate it.

**Comment by prisis** [comment]
@KaneCohen done.

**Pull request merged**
